apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: nexusameer/voting-app-worker:latest
          name: worker
          resources:
            requests:
              cpu: "5m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
