- name: Cleanup Voting App
  hosts: all
  gather_facts: false

  tasks:
    - name: Delete namespace
      ansible.builtin.command: kubectl delete ns voting
      failed_when: false

    - name: Delete postgres PV
      ansible.builtin.command: kubectl delete pv postgres-pv
      failed_when: false
